version: "3.8"

services:
  snowhrest:
    container_name: snowhrest
    build:
      context: .
      dockerfile: ./Dockerfile_snowhrest
    restart: unless-stopped
    stdin_open: true
    tty: true
    ports:
      - 3000:3000
    environment:
      - HCLI_PAYER: <change_me>
      - HCLI_PAYERPRIVKEY: <change_me>
      - HCLI_NETWORK=testnet
    volumes:
      - <local path to certificates>:/hrest/certs
      - <local path to wallets>:/hrest/wallets
      - <local path to users>:/hrest/users
