version: "3.8"

services:
  snowhrest:
    container_name: snowhrest
    build:
      dockerfile: ./Dockerfile_snowhrest
    restart: unless-stopped
    stdin_open: true
    tty: true
    ports:
      - 3000:3000
    environment:
      HCLI_PAYER=/run/secrets/hcli_payer
      HCLI_PAYERPRIVKEY=/run/secrets/hcli_payerprivkey
      HCLI_NETWORK=testnet
    volumes:
      - <local path to certificates>:/hrest/certs
      - <local path to wallets>:/hrest/wallets
      - <local path to users>:/hrest/users
    secrets:
      - hcli_payer
      - hcli_payerprivkey

secrets:
  hcli_payer:
    file: ./secret.hcli_payer.txt
  hcli_payerprivkey:
    file: ./secret.hcli_payerprivkey.txt
